### PR TITLE
Use kramdown to generate the ToC for the manual

### PR DESCRIPTION
**Pull request by ZakCodes**
To make sure there are no errors in the ToC, I've changed the ToC of the manual to be auto-generated on a site build by [kramdown]. 

For details on how to use [kramdown] to generate a ToC and exclude certain headlines see [the documentation here](https://kramdown.gettalong.org/converter/html.html#toc).

I've looked at the difference of the site built before and after this commit and the only difference is that I've removed the `<!-- TOC -->` comments and the ToC's root elements and all the elements of the ToC have IDs.

[kramdown]: https://kramdown.gettalong.org/

### CODE REVIEW

**Comment by baconpaul** [comment]
Thank you

We don’t need to change our gemfile? Does git have kramdown installed by default? I suppose I could merge it and find out :) but figured I would ask first

Very much appreciate this contribution. Tagging @vinceyzed also

**Comment by kzantow** [comment]
@baconpaul looks to be the default processor for Jekyll 3.0 https://help.github.com/en/articles/updating-your-markdown-processor-to-kramdown

**Comment by baconpaul** [comment]
Super! Then let’s merge. I’m sure we will all be way happier!

Thank you very much!

**Comment by VincyZed** [comment]
Great to have this built-in solution instead of relying on a plugin in a text editor. Thanks a lot!

**Comment by ZakCodes** [comment]
You're welcome!  
kramdown is indeed the default markdown converter for Jekyll 3.0 as well as 4.0 by the way. However, [Jekyll 3.0 uses kramdown v1.x and 4.0 now uses kramdown v2.x](https://jekyllrb.com/docs/upgrading/3-to-4/#kramdown-v2).

**Pull request merged**
