### PR TITLE
add bittage to windows and add 32-bit build too

### PR DESCRIPTION
**Pull request by esaruoho**
this .. should .. allow for showing 32-bit downloads too.

### CODE REVIEW

**Comment by esaruoho** [comment]
image
image

**Comment by esaruoho** [comment]
You're right, there's no point in having the windows orange button twice. editing out.

**Comment by esaruoho** [comment]
maybe this is better? @itsmedavep ?
image

**Comment by itsmedavep** [comment]
Looks good to me!

**Pull request merged**
