### PR TITLE
contributors anchor

### PR DESCRIPTION
**Pull request by esaruoho**
this adds #contributors as anchor

### CODE REVIEW

**Comment by esaruoho** [comment]
to allow for directing a user, with the following link, directly to the contributors portion of the main site :)
http://surge-synthesizer.github.io/#contributors

**Comment by esaruoho** [comment]
screenshot:
surge

**Comment by itsmedavep** [comment]
Nice! That is super useful. Does it do the same thing if you put those on the contribution section as opposed to the label?

It’s a web semantics thing. A tags are meant as links. 

I would have added what you did to the parent. So I was making your addition I would have added your stuff to the content creators section and not the heading.

**Comment by esaruoho** [comment]
@itsmedavep i think it might! i just wanted to do it quickly and dump it somewhere, without it breaking stuff. i'm sure there could be more anchors added, and, as suggested on the general-slack, there could be like "system requirements" and "contributors" at the top menu. i'm not sure how to do it gorgeously, but it'd be a nice thing to do.
i can try and add it (contributors anchor) to the section itself and see if it works?

**Comment by esaruoho** [comment]
thanks, your way is way better! i'll do that :)

**Comment by esaruoho** [comment]
@itsmedavep done! merged in. thanks, i think i just learned new stuff about html

**Pull request merged**
