### PR TITLE
chore: add includes for release links and text

### PR DESCRIPTION
**Pull request by kzantow**
Also tweaked the download section just a bit, wdyt @itsmedavep @baconpaul ?

image

### CODE REVIEW

**Comment by baconpaul** [comment]
I think that looks absolutely great. I would just add the text "Last updated on" before the date and time.

Also: Do you have a machine readable form of that date on a URL somewhere? Then I could make a menu item which does the start of check-for-upgrades

**Comment by kzantow** [comment]
@baconpaul if you want a specific format for the build date/time i can output it. It would be available like this: https://raw.githubusercontent.com/surge-synthesizer/surge-synthesizer.github.io/master/_includes/latest_build_time

**Comment by kzantow** [comment]
There would also be https://raw.githubusercontent.com/surge-synthesizer/surge-synthesizer.github.io/master/_includes/stable_build_version you could check for new stable releases.

**Comment by baconpaul** [comment]
YYYYMMDDHHSS in a text file with a stable URL is fine with me! Thanks!

**Comment by itsmedavep** [comment]
AMAZING! Thank you. This is great.

**Pull request merged**
